image: node:7.5
pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - mv src/ public/
  - mv node_modules/ public/node_modules
  - cp public/index.html public/404.html
  artifacts:
    paths:
    - public
  only:
  - master
