image: node:7.5
pages:
  stage: deploy
  script:
  - npm install
  - npm install -g @angular/cli
  - ng build -prod
  - mv dist/ public/
  - cp public/index.html public/404.html
  artifacts:
    paths:
    - public
  only:
  - master
